# Generated by Django 4.1.6 on 2023-08-02 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_date_of_last_watch_and_more'),
        ('shows', '0003_alter_episode_options_alter_season_options_and_more'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodecomment',
            name='episode',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.episode'),
        ),
        migrations.AddField(
            model_name='episodecomment',
            name='profile',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='episodecomment',
            name='text',
            field=models.TextField(default='plainText', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episodecomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episoderating',
            name='episode',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.episode'),
        ),
        migrations.AddField(
            model_name='episoderating',
            name='profile',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='episoderating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='episoderating',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriescomment',
            name='profile',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='seriescomment',
            name='series',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.series'),
        ),
        migrations.AddField(
            model_name='seriescomment',
            name='text',
            field=models.TextField(default='plainText', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriescomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesrating',
            name='profile',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='seriesrating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='seriesrating',
            name='series',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.series'),
        ),
        migrations.AddField(
            model_name='seriesrating',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
