# Generated by Django 4.1.6 on 2023-08-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_last_watch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number_of_episodes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number_of_shows',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shows_added',
        ),
    ]
