# Generated by Django 4.1.6 on 2023-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_episode_options_alter_season_options_and_more'),
        ('accounts', '0002_remove_profile_date_of_last_watch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_last_watch',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_episodes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_shows',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='shows_added',
            field=models.ManyToManyField(to='shows.series'),
        ),
    ]
