# Generated by Django 4.1.6 on 2023-08-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.PositiveSmallIntegerField(default=0)),
                ('episode_id', models.CharField(default='', max_length=128)),
                ('episode_title', models.CharField(default='', max_length=128)),
                ('year', models.PositiveBigIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['episode'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('title_id', models.CharField(default='', max_length=64, unique=True)),
                ('rating', models.FloatField(default=0)),
                ('image', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.episode')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.series')),
            ],
            options={
                'ordering': ['episode__season__season', 'episode__episode'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField(default=0)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='shows.series')),
            ],
            options={
                'ordering': ['season'],
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='shows.season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.series'),
        ),
    ]
