# Generated by Django 4.1.6 on 2023-08-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={},
        ),
        migrations.AlterModelOptions(
            name='watchedepisode',
            options={},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='episode_id',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='episode_title',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='series',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='year',
        ),
        migrations.RemoveField(
            model_name='season',
            name='season',
        ),
        migrations.RemoveField(
            model_name='season',
            name='series',
        ),
        migrations.RemoveField(
            model_name='series',
            name='image',
        ),
        migrations.RemoveField(
            model_name='series',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='series',
            name='title',
        ),
        migrations.RemoveField(
            model_name='series',
            name='title_id',
        ),
        migrations.RemoveField(
            model_name='watchedepisode',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='watchedepisode',
            name='series',
        ),
        migrations.RemoveField(
            model_name='watchedepisode',
            name='timestamp',
        ),
    ]
