# Generated by Django 4.1.6 on 2023-02-19 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_episode_season_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.series'),
        ),
        migrations.AddField(
            model_name='episode',
            name='year',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='season',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='series',
            name='title_id',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
