# Generated by Django 4.1.6 on 2023-08-02 17:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_date_of_last_watch_and_more'),
        ('shows', '0002_alter_episode_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['season']},
        ),
        migrations.AlterModelOptions(
            name='watchedepisode',
            options={'ordering': ['episode__season__season', 'episode__episode']},
        ),
        migrations.AddField(
            model_name='episode',
            name='episode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='episode',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='shows.season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.series'),
        ),
        migrations.AddField(
            model_name='episode',
            name='year',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='season',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='shows.series'),
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='series',
            name='title_id',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='watchedepisode',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.episode'),
        ),
        migrations.AddField(
            model_name='watchedepisode',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='watchedepisode',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.series'),
        ),
        migrations.AddField(
            model_name='watchedepisode',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
