# Generated by Django 4.1.6 on 2023-02-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_episodecomment_seriescomment_watchedepisode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['season']},
        ),
        migrations.AlterModelOptions(
            name='watchedepisode',
            options={'ordering': ['episode__season__season', 'episode__episode']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='shows.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='shows.series'),
        ),
    ]
